#!/usr/bin/env node

/**
 * Pre-build script to obfuscate Turnstile site key
 *
 * This script runs before the build process and creates an obfuscated
 * version of the site key that will be embedded in the application.
 */

const fs = require('fs');
const path = require('path');
const AdvancedObfuscator = require('./obfuscate.cjs');

const ENV_FILE = path.join(__dirname, '..', '.env');
const ENV_LOCAL_FILE = path.join(__dirname, '..', '.env.local');

function loadEnvFile(filepath) {
  if (!fs.existsSync(filepath)) {
    return {};
  }

  const content = fs.readFileSync(filepath, 'utf-8');
  const env = {};

  content.split('\n').forEach(line => {
    const match = line.match(/^([^=:#]+)=(.*)$/);
    if (match) {
      const key = match[1].trim();
      let value = match[2].trim();

      // Remove quotes if present
      if ((value.startsWith('"') && value.endsWith('"')) ||
          (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1);
      }

      env[key] = value;
    }
  });

  return env;
}

function main() {
  console.log('[Pre-build] Starting Turnstile key obfuscation...\n');

  // Load environment variables
  const env = {
    ...loadEnvFile(ENV_FILE),
    ...loadEnvFile(ENV_LOCAL_FILE),
    ...process.env
  };

  const siteKey = env.VITE_TURNSTILE_SITE_KEY;

  if (!siteKey) {
    console.warn('[Pre-build] WARNING: VITE_TURNSTILE_SITE_KEY not found!');
    console.warn('[Pre-build] Using test key for build...\n');
    return;
  }

  console.log(`[Pre-build] Found site key: ${siteKey.substring(0, 10)}...`);

  // Obfuscate the site key
  const obfuscator = new AdvancedObfuscator();
  const obfuscated = obfuscator.obfuscate(siteKey);

  // Write to .env.local (which takes precedence)
  const envContent = `# Auto-generated by prebuild script - DO NOT EDIT
# This file is gitignored and regenerated on each build
VITE_TURNSTILE_OBFUSCATED='${JSON.stringify(obfuscated)}'
`;

  fs.writeFileSync(ENV_LOCAL_FILE, envContent);

  console.log(`\n[Pre-build] ✓ Obfuscated payload written to .env.local`);
  console.log(`[Pre-build] ✓ Payload size: ${JSON.stringify(obfuscated).length} bytes`);
  console.log('[Pre-build] ✓ Ready for build!\n');
}

if (require.main === module) {
  main();
}

module.exports = main;
