name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your primary branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the React app
      - name: Build project
        run: npm run build

      # Step 5: Add custom domain (CNAME)
      - name: Add CNAME file
        run: |
          mkdir -p build
          echo "www.koes.ch" > build/CNAME

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_GITHUB_TOKEN }}
          publish_dir: ./build
